// Program defaults
pub const PROGRAM_PRETEXT: &str = r#"// This file is autogenerated with https://github.com/acheroncrypto/native-to-anchor

use anchor_lang::prelude::*;

declare_id!("11111111111111111111111111111111");

#[program]
pub mod <ProgramName> {
use super::*;

"#;
pub const SKIP_LINE: [&str; 9] = [
    "///",
    "#[allow(dead_code)]",
    "#[deprecated",
    "#[serde(",
    "#[cfg",
    "since =",
    "note =",
    ")]",
    "Reserved",
];
pub const DEFAULT_ARGS: [&str; 5] = ["u16", "u32", "u64", "bool", "[u64; 8]"];
pub const ACCOUNT_SPLIT: [&str; 8] = [
    "_pubkey",
    "_key",
    "_pk",
    ".unwrap",
    "_id",
    "::id",
    "::ID",
    "::default",
];
pub const ACCOUNT_TRAITS: [&str; 4] = ["Pack", "Sealed", "IsInitialized", "AccountMaxSize"];
